name: Tailwind CSS Build

on:
  push:
    branches:
      - main # Ganti dengan branch utama Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Tailwind CSS build
      run: npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch